version: '3'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      GIT_CONFIG_URL: $GIT_CONFIG_URL
    image: sace/service-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      
  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sace/service-discovery
    restart: always
    ports:
      - 8761:8000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://registry:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - config